---
- name: Install EasyRSA and use it to generate a X.509 cert & key
  hosts: localhost
  tasks:
    - name: Clone EasyRSA repo
      git:
        repo: https://github.com/OpenVPN/easy-rsa.git
        dest: "{{ playbook_dir }}/easy-rsa" 
    - name: Check if EasyRSA has been initialized before
      stat:
        path: "{{ playbook_dir }}/pki"
      register: easyrsa_pki
    - name: Initialize EasyRSA
      shell: "{{ playbook_dir }}/easy-rsa/easyrsa3/easyrsa init-pki"
      when: easyrsa_pki.stat.exists == false
      #- name: Enable EasyRSA batch mode (no interactive prompts)
      #shell: "export EASYRSA_BATCH=1"
    - name: Generate Signing Request
      shell: "{{ playbook_dir }}/easy-rsa/easyrsa3/easyrsa gen-req {{ entity_name }} nopass"
      environment:
        EASYRSA_BATCH: 1
